version: '3.8'

services:
  project-sleepy:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./project-sleepy/states/config.php:/var/www/html/states/config.php
      - ./project-sleepy/states/cache.json:/var/www/html/states/cache.json
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped 